### ISSUE TITLE
Create a new NPM release

### ISSUE THREAD

**Issue by ldidry** [Pita/ueberDB#101]
According to https://www.npmjs.com/package/ueberDB, the latest release is 3 years old. It may be good to create a new release, no? And ueberdb2 is 2 years old.

**Comment by ldidry** [comment]
Ping @JohnMcLear

**Comment by JohnMcLear** [comment]
Added @ldidry as package owner.

**Comment by ldidry** [comment]
Thx !

**Comment by knowtheory** [comment]
Hey you two, happy to lend a hand if there's anything i can do (as seen from the mention above, we've got a ticket open to track this very issue)!

**Comment by ldidry** [comment]
I tried to publish the new version with my usual npmjs account ([framasky](https://npmjs.com/~framasky)), fail. I created a `ldidry` account (why isn't there a real link between github and npmjs.com?), same fail.

@JohnMcLear Could give me the rights to publish the package on npmjs.com with the `framasky` account please?

**Comment by JohnMcLear** [comment]
?done


Secret, Proprietary & Confidential

This electronic message transmission contains information which is proprietary and confidential. The information is intended solely for the intended recipient, and use by any other party is not authorized.
________________________________

**Comment by ldidry** [comment]
Since the package is now published under the ueberdb2 name, could you give me the rights on it too please?

**Comment by JohnMcLear** [comment]
done

**Comment by ldidry** [comment]
Thank you, it's released for ueberdb2 (since ueberDB is 3 years old, and that Etherpad uses ueberdb2, it may not be necessary to release ueberDB, is it?)

**Comment by knowtheory** [comment]
Thank you so much you two!  And thank you so much for keeping interesting gear like EtherpadLite rolling :)
