### ISSUE TITLE
Why limiting keys to 100 chars ?

### ISSUE THREAD

**Issue by kapouer** [Pita/ueberDB#73]
I need to store url as keys. 100 chars is not enough and artificially limiting (most sql indexes are fine with huge keys). Is this some kind of lowest common denominator ?

**Comment by Pita** [comment]
It's hard to change cause you would have to migrate all existing running instances. And yes the idea is also to have it as the lowest common denominator. Maybe you want to consider hashing the urls. Whats your exact use case?

**Comment by kapouer** [comment]
Nothing in particular, but yes hashing is a workaround.
Maybe ueberDB could do that hash as soon as keys are > 100 in length.

**Comment by JohnMcLear** [comment]
How would hashing work?  Seems to make sense to me but it could confuse Admins..  Re why its a database AFAIK redis feature...

On 19 Feb 2015 08:02, =?ISO-8859-1?Q?J=E9r=E9my_Lal?= <notifications@github.com> wrote:

Nothing in particular, but yes hashing is a workaround.
Maybe ueberDB could do that hash as soon as keys are > 100 in length.
